# Generated by Django 5.1.7 on 2025-10-03 18:49

import core.models.usuario.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titular', models.CharField(default='', max_length=45, verbose_name='Nome do Titular')),
                ('numero_cartao', models.CharField(default='', max_length=20, verbose_name='Número do Cartão')),
                ('data_de_validade', models.CharField(default='', max_length=7, verbose_name='Data de Validade')),
                ('cvv', models.CharField(default='', max_length=4, verbose_name='CVV')),
                ('bandeira', models.CharField(default='', max_length=20, verbose_name='Bandeira')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100, verbose_name='Nome do Categoria')),
                ('descricao', models.TextField(default='', verbose_name='Descrição do Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(default='', max_length=45, verbose_name='Bairro')),
                ('rua', models.CharField(default='', max_length=45, verbose_name='Rua')),
                ('numero', models.CharField(default='', max_length=10, verbose_name='Número')),
                ('cep', models.CharField(default='', max_length=10, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='Complemento')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('passage_id', models.CharField(blank=True, help_text='Passage ID', max_length=255, null=True, verbose_name='passage_id')),
                ('email', models.EmailField(help_text='Email', max_length=255, unique=True, verbose_name='email')),
                ('name', models.CharField(blank=True, help_text='Username', max_length=255, null=True, verbose_name='name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('perfil', models.CharField(choices=[('usuario', 'Usuário'), ('administrador', 'Administrador')], default='usuario', help_text='Tipo de perfil do usuário', max_length=20, verbose_name='perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('endereco', models.ForeignKey(blank=True, help_text='Endereço do usuário', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='core.endereco', verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', core.models.usuario.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cartao', verbose_name='Cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Validade do Pedido')),
                ('status', models.IntegerField(choices=[(1, 'Carrinho'), (2, 'Realizado'), (3, 'Pago'), (4, 'Entregue')], default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_de_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.metododepagamento', verbose_name='Método de Pagamento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pedido', verbose_name='Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('nome', models.CharField(default='', max_length=100, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(default='', verbose_name='Descrição do Produto')),
                ('quantidade_em_estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto')),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoria do produto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.produto', verbose_name='Produto')),
            ],
        ),
    ]
