# Generated by Django 5.1.7 on 2025-10-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='identificador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
