# Generated by Django 5.1.7 on 2025-11-03 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 3, 17, 6, 41, 994768, tzinfo=datetime.timezone.utc), verbose_name='Data de criação do pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_de_retirada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Retirada do Pedido'),
        ),
    ]
