# Generated by Django 5.1.7 on 2025-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_data_criacao_alter_pedido_data_de_retirada'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ultimo_pedido',
            field=models.DateTimeField(blank=True, help_text='Data do último pedido realizado pelo usuário', null=True, verbose_name='Último pedido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Nome do usuário', max_length=255, null=True, verbose_name='name'),
        ),
    ]
