# Generated by Django 5.1.7 on 2025-11-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_ultimo_pedido_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
