# Generated by Django 5.1.7 on 2025-06-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Pessoa',
        ),
    ]
