# Generated by Django 5.1.7 on 2025-06-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_usuario_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='exemplo@gmail.com', max_length=45, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='', max_length=45, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone'),
        ),
    ]
