# Generated by Django 5.1.7 on 2025-06-01 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_pessoa_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titular', models.CharField(default='', max_length=45, verbose_name='Nome do Titular')),
                ('numero_cartao', models.CharField(default='', max_length=20, verbose_name='Número do Cartão')),
                ('data_de_validade', models.CharField(default='', max_length=7, verbose_name='Data de Validade')),
                ('cvv', models.CharField(default='', max_length=4, verbose_name='CVV')),
                ('bandeira', models.CharField(default='', max_length=20, verbose_name='Bandeira')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cartao', verbose_name='Cartão'),
        ),
    ]
