# Generated by Django 5.1.7 on 2025-06-12 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cartao_pessoa_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.ForeignKey(blank=True, help_text='Endereço do usuário', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='core.endereco', verbose_name='endereço'),
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
