# Generated by Django 5.1.7 on 2025-06-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_endereco_delete_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('nome', models.CharField(default='', max_length=100, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(default='', verbose_name='Descrição do Produto')),
                ('quantidade_em_estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
            ],
        ),
    ]
