# Generated by Django 5.1.7 on 2025-06-12 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100, verbose_name='Nome do Categoria')),
                ('descricao', models.TextField(default='', verbose_name='Descrição do Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria do produto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.categoria', verbose_name='Categoria'),
        ),
    ]
