# Generated by Django 5.1.7 on 2025-06-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_categoria_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
    ]
