# Generated by Django 5.1.7 on 2025-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Total do Pedido')),
                ('data_de_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Validade do Pedido')),
                ('status', models.CharField(default='Pendente', max_length=20, verbose_name='Status do Pedido')),
            ],
        ),
    ]
