# Generated by Django 5.1.7 on 2025-06-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cartao', verbose_name='Cartao')),
            ],
        ),
        migrations.AddField(
            model_name='pagamento',
            name='metodo_de_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.metododepagamento', verbose_name='Método de Pagamento'),
        ),
    ]
