# Generated by Django 5.1.7 on 2025-07-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_passage_id_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passage_id',
            field=models.CharField(blank=True, help_text='Passage ID', max_length=255, null=True, verbose_name='passage_id'),
        ),
    ]
