# Generated by Django 5.1.7 on 2025-07-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_user_passage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
    ]
