# Generated by Django 5.1.7 on 2025-07-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_pedido_status_remove_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='preco_total',
        ),
    ]
