# Generated by Django 5.1.7 on 2025-07-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_pedido_preco_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.produto', verbose_name='Produto'),
        ),
    ]
