# Generated by Django 5.1.7 on 2025-07-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_pedido_status_pedido_usuario_alter_itempedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
