# Generated by Django 5.1.7 on 2025-07-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('usuario', 'Usuário'), ('vendedor', 'Vendedor'), ('administrador', 'Administrador')], default='usuario', help_text='Tipo de perfil do usuário', max_length=20, verbose_name='perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
