# Generated by Django 5.1.7 on 2025-07-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_user_perfil_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('usuario', 'Usuário'), ('administrador', 'Administrador')], default='usuario', help_text='Tipo de perfil do usuário', max_length=20, verbose_name='perfil'),
        ),
    ]
